### ISSUE TITLE
sitemesh issue.

### ISSUE THREAD

**Issue by tsengyi** [izeye/samples-spring-boot-branches#2]
Hi, I update the lastest spring boot version : 1.3.2.RELEASE, 

then show below error in page with sitemesh, has you any idea?

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Sat Feb 06 15:52:38 CST 2016
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by izeye** [comment]
@tsengyi  Since Spring Boot 1.3.0, application properties for view prefix/suffix have been changed from `spring.view.prefix` to `spring.mvc.view.prefix`.

See 0d46fa6 and http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-customize-view-resolvers
